<template>
  <b-card header="Note">
    <ul>
      <li>Plan(editing one) and Profile(stored) are the same (Sorry for confusion)</li>
      <li><strong>Your plan won't save into profile unless you press Save button or switch to a different profile. (Auto Save when switching)</strong></li>
      <li>So you can always <strong>reload your plan</strong> before saving.</li>
      <li>Snapshot will take your current state (before saving) and create a new Profile</li>
    </ul>
    <h6>Import Plan</h6>
    <p class="card-text">
      To import a plan, click on the link that generated by others or by yourself and Organizer will handle that for you.
    </p>
    <h6>Edit Plan Name</h6>
    <p class="card-text">
      You can edit current plan name at Export Tab, or at the time you import your plan.
    </p>
  </b-card>
</template>
